# Generated by Django 4.2.7 on 2023-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Nombre de la empresa')),
                ('address', models.CharField(max_length=30, verbose_name='Direccion de la empresa')),
                ('rut', models.AutoField(primary_key=True, serialize=False, verbose_name='RUT de la empresa')),
                ('phone', models.IntegerField(verbose_name='Telefono de la empresa')),
            ],
        ),
    ]
