# Generated by Django 4.2.7 on 2023-11-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('full_name', models.CharField(max_length=60, verbose_name='Nombre completo del empleado')),
                ('rut', models.AutoField(primary_key=True, serialize=False, verbose_name='RUT del empleado')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del empleado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.company', verbose_name='Empresa del empleado')),
            ],
        ),
    ]
